import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  Menubar,
  MenubarMenu,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarTrigger,
} from "@/components/ui/menubar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menubar className={"p-5"}>
          <MenubarMenu>
            <MenubarTrigger>Todos</MenubarTrigger>
            <MenubarRadioGroup value="benoit" className="flex ml-10 gap-2">
              <Link href={"/add-Todos"} className="bg-amber-600 text-white p-1">
                Add Todos
              </Link>
              <Link href={"/show-Todos"} className="bg-red-600 text-white p-1">
                Show Todos
              </Link>
            </MenubarRadioGroup>
          </MenubarMenu>
        </Menubar>
        {children}
      </body>
    </html>
  );
}
