import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WrapperNavBar from "@/components/ui/WrapperNavBar";
import { currentUser } from "./actions/addUser";
import SideBar from "@/components/ui/SIdeBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pinterest",
  description: "Generated by Pankaj",
};

export default async function RootLayout({ children }) {
  const res = await currentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <WrapperNavBar />

        <div className="flex h-[calc(100vh-64px)] w-full overflow-hidden">
          {res && (
            <aside className="w-[80px] border-r border-gray-200">
              <SideBar />
            </aside>
          )}

          <main className="flex-1 overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
